# frozen_string_literal: true
#
# Jekyll Generator: recent posts sorted by last_modified_at.
# Page 1 is served by _tabs/recent.md (this generator only injects data into it).
# Pages 2+ are generated by this generator.
#

module Jekyll
  class RecentPostsGenerator < Generator
    safe true
    priority :low

    def generate(site)
      now = Time.now
      one_week_ago = now - (7 * 24 * 60 * 60)
      per_page = site.config['paginate'] || 10

      # Build effective lastmod
      posts_with_lastmod = site.posts.docs.map do |post|
        lm = post.data['last_modified_at']
        lastmod = if lm && !lm.to_s.strip.empty?
                    Time.parse(lm.to_s.strip)
                  rescue
                    post.date
                  else
                    post.date
                  end
        { post: post, lastmod: lastmod }
      end

      sorted = posts_with_lastmod.sort_by { |e| e[:lastmod] }.reverse

      # Step 1: all posts modified in the last week
      recent = sorted.select { |e| e[:lastmod] >= one_week_ago }

      # Step 2: fill to per_page if fewer than 10
      if recent.length < per_page
        already_ids = recent.map { |e| e[:post].id }
        supplement = sorted.reject { |e| already_ids.include?(e[:post].id) }
                           .first(per_page - recent.length)
        recent.concat(supplement)
      end

      total_pages = (recent.length.to_f / per_page).ceil

      # -- Page 1: inject into _tabs/recent.md page --
      tab_page = site.pages.find { |p| p.name == 'recent.md' || p.path&.end_with?('recent.md') }
      if tab_page
        page1_posts = recent[0, per_page].map { |e| e[:post] }
        tab_page.data['posts'] = page1_posts
        tab_page.data['paginator'] = build_paginator(1, total_pages, page1_posts, '/recent/',
          total_pages > 1 ? '/recent/page2/' : nil)
        tab_page.data['layout'] = 'recent'  # ensure correct layout
        tab_page.content = ''               # clear content so layout renders the list
      end

      # -- Pages 2+ : generate as new pages --
      (2..total_pages).each do |page_num|
        slice = recent[(page_num - 1) * per_page, per_page]
        posts = slice.map { |e| e[:post] }

        dir = "recent/page#{page_num}"
        prev_path = page_num == 2 ? '/recent/' : "/recent/page#{page_num - 1}/"
        next_path = page_num < total_pages ? "/recent/page#{page_num + 1}/" : nil

        site.pages << RecentPage.new(site, dir, page_num, posts, total_pages, prev_path, next_path)
      end

      Jekyll.logger.info "RecentPosts:", "#{recent.length} posts → #{total_pages} page(s)"
    end

    private

    def build_paginator(page, total, posts, prev_path, next_path)
      {
        'page' => page, 'total_pages' => total,
        'posts' => posts,
        'previous_page' => page > 1 ? page - 1 : nil,
        'next_page' => page < total ? page + 1 : nil,
        'previous_page_path' => page > 1 ? prev_path : nil,
        'next_page_path' => next_path
      }
    end
  end

  class RecentPage < Page
    def initialize(site, dir, page_num, posts, total_pages, prev_path, next_path)
      @site = site
      @base = site.source
      @dir  = dir
      @name = 'index.html'
      self.process(@name)

      self.data['layout']    = 'recent'
      self.data['title']     = "最近 — 第 #{page_num} 页"
      self.data['posts']     = posts
      self.data['paginator'] = {
        'page' => page_num, 'total_pages' => total_pages,
        'posts' => posts,
        'previous_page' => page_num > 1 ? page_num - 1 : nil,
        'next_page' => page_num < total_pages ? page_num + 1 : nil,
        'previous_page_path' => prev_path,
        'next_page_path' => next_path
      }
      self.content = ''
    end
  end
end
